### PR TITLE
chore(image): update CentOS image to v20161027

### PR DESCRIPTION
**Pull request by sbolel**
### Summary of Changes

- update centos image version from `v20160921` to `v20161027`

### CODE REVIEW

**Comment by ajazam** [comment]
hello @sbolel. Has the installation procedure been tested with the new version of the centos image?

**Comment by sbolel** [comment]
Hi @ajazam! I have a cluster running with the new image with no issues!

**Comment by ajazam** [comment]
Great. Thank you.

**Comment by sbolel** [comment]
My pleasure @ajazam! Thank you for your help.

**Pull request merged**
